// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace IrServiceHost.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CarInsuredValue
    {
        /// <summary>
        /// Initializes a new instance of the CarInsuredValue class.
        /// </summary>
        public CarInsuredValue() { }

        /// <summary>
        /// Initializes a new instance of the CarInsuredValue class.
        /// </summary>
        public CarInsuredValue(double? newCarPrice = default(double?), double? sumInsured = default(double?))
        {
            NewCarPrice = newCarPrice;
            SumInsured = sumInsured;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "newCarPrice")]
        public double? NewCarPrice { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sumInsured")]
        public double? SumInsured { get; set; }

    }
}
