// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace IrServiceHost.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CarPrice
    {
        /// <summary>
        /// Initializes a new instance of the CarPrice class.
        /// </summary>
        public CarPrice() { }

        /// <summary>
        /// Initializes a new instance of the CarPrice class.
        /// </summary>
        public CarPrice(double? catalogPrice = default(double?), double? currentPrice = default(double?))
        {
            CatalogPrice = catalogPrice;
            CurrentPrice = currentPrice;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "catalogPrice")]
        public double? CatalogPrice { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "currentPrice")]
        public double? CurrentPrice { get; set; }

    }
}
