// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace IrServiceHost.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CarPremiumFactors
    {
        /// <summary>
        /// Initializes a new instance of the CarPremiumFactors class.
        /// </summary>
        public CarPremiumFactors() { }

        /// <summary>
        /// Initializes a new instance of the CarPremiumFactors class.
        /// </summary>
        public CarPremiumFactors(string regularDriver = default(string), CarObject car = default(CarObject), MostFrequentDriverViewModel driver = default(MostFrequentDriverViewModel))
        {
            RegularDriver = regularDriver;
            Car = car;
            Driver = driver;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "regularDriver")]
        public string RegularDriver { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "car")]
        public CarObject Car { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "driver")]
        public MostFrequentDriverViewModel Driver { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.Driver != null)
            {
                this.Driver.Validate();
            }
        }
    }
}
