// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace IrServiceHost.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CarPayment
    {
        /// <summary>
        /// Initializes a new instance of the CarPayment class.
        /// </summary>
        public CarPayment() { }

        /// <summary>
        /// Initializes a new instance of the CarPayment class.
        /// </summary>
        public CarPayment(string paymentFrequency = default(string))
        {
            PaymentFrequency = paymentFrequency;
        }

        /// <summary>
        /// Possible values include: 'Unknown', 'Monthly', 'Quarter',
        /// 'SemiAnnual', 'Annual'
        /// </summary>
        [JsonProperty(PropertyName = "paymentFrequency")]
        public string PaymentFrequency { get; set; }

    }
}
