// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace IrServiceHost.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CarViewModel
    {
        /// <summary>
        /// Initializes a new instance of the CarViewModel class.
        /// </summary>
        public CarViewModel() { }

        /// <summary>
        /// Initializes a new instance of the CarViewModel class.
        /// </summary>
        public CarViewModel(CarPremiumFactors premiumFactors = default(CarPremiumFactors), CarPayment payment = default(CarPayment))
        {
            PremiumFactors = premiumFactors;
            Payment = payment;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "premiumFactors")]
        public CarPremiumFactors PremiumFactors { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "payment")]
        public CarPayment Payment { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.PremiumFactors != null)
            {
                this.PremiumFactors.Validate();
            }
        }
    }
}
