// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace IrServiceHost.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ReturnObjectZipCode
    {
        /// <summary>
        /// Initializes a new instance of the ReturnObjectZipCode class.
        /// </summary>
        public ReturnObjectZipCode() { }

        /// <summary>
        /// Initializes a new instance of the ReturnObjectZipCode class.
        /// </summary>
        public ReturnObjectZipCode(IList<string> errorMessages = default(IList<string>), ZipCode objectProperty = default(ZipCode), bool? hasErrors = default(bool?))
        {
            ErrorMessages = errorMessages;
            ObjectProperty = objectProperty;
            HasErrors = hasErrors;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "errorMessages")]
        public IList<string> ErrorMessages { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "object")]
        public ZipCode ObjectProperty { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hasErrors")]
        public bool? HasErrors { get; private set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.ObjectProperty != null)
            {
                this.ObjectProperty.Validate();
            }
        }
    }
}
