// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace IrServiceHost.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ReturnObjectListString
    {
        /// <summary>
        /// Initializes a new instance of the ReturnObjectListString class.
        /// </summary>
        public ReturnObjectListString() { }

        /// <summary>
        /// Initializes a new instance of the ReturnObjectListString class.
        /// </summary>
        public ReturnObjectListString(IList<string> errorMessages = default(IList<string>), IList<string> objectProperty = default(IList<string>), bool? hasErrors = default(bool?))
        {
            ErrorMessages = errorMessages;
            ObjectProperty = objectProperty;
            HasErrors = hasErrors;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "errorMessages")]
        public IList<string> ErrorMessages { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "object")]
        public IList<string> ObjectProperty { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hasErrors")]
        public bool? HasErrors { get; private set; }

    }
}
