// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace IrServiceHost.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ZipCode
    {
        /// <summary>
        /// Initializes a new instance of the ZipCode class.
        /// </summary>
        public ZipCode() { }

        /// <summary>
        /// Initializes a new instance of the ZipCode class.
        /// </summary>
        public ZipCode(string zipcodeProperty = default(string))
        {
            ZipcodeProperty = zipcodeProperty;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "zipcode")]
        public string ZipcodeProperty { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.ZipcodeProperty != null)
            {
                if (!System.Text.RegularExpressions.Regex.IsMatch(this.ZipcodeProperty, "^[1-9][0-9]{3}[A-Z]{2}$"))
                {
                    throw new ValidationException(ValidationRules.Pattern, "ZipcodeProperty", "^[1-9][0-9]{3}[A-Z]{2}$");
                }
            }
        }
    }
}
