// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace IrServiceHost
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for ApiCarPremiumPolicyGetVariants.
    /// </summary>
    public static partial class ApiCarPremiumPolicyGetVariantsExtensions
    {
            /// <summary>
            /// Get Product Variants
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewModel'>
            /// Viewmodel containg licenseplate, driver-age, -damagefreeyears and
            /// -residenceaddress zipcode
            /// </param>
            public static void OldPost(this IApiCarPremiumPolicyGetVariants operations, CarViewModel viewModel = default(CarViewModel))
            {
                Task.Factory.StartNew(s => ((IApiCarPremiumPolicyGetVariants)s).OldPostAsync(viewModel), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get Product Variants
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='viewModel'>
            /// Viewmodel containg licenseplate, driver-age, -damagefreeyears and
            /// -residenceaddress zipcode
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task OldPostAsync(this IApiCarPremiumPolicyGetVariants operations, CarViewModel viewModel = default(CarViewModel), CancellationToken cancellationToken = default(CancellationToken))
            {
                await operations.OldPostWithHttpMessagesAsync(viewModel, null, cancellationToken).ConfigureAwait(false);
            }

    }
}
