// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace IrServiceHost
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// ApiCarPremiumPolicyGetVariants operations.
    /// </summary>
    public partial interface IApiCarPremiumPolicyGetVariants
    {
        /// <summary>
        /// Get Product Variants
        /// </summary>
        /// <param name='viewModel'>
        /// Viewmodel containg licenseplate, driver-age, -damagefreeyears and
        /// -residenceaddress zipcode
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> OldPostWithHttpMessagesAsync(CarViewModel viewModel = default(CarViewModel), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
    }
}
