// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace IrServiceHost
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Documentation on the services for InsuranceRight
    /// </summary>
    public partial interface IIrServiceHostClient : IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }

        /// <summary>
        /// Subscription credentials which uniquely identify client
        /// subscription.
        /// </summary>
        ServiceClientCredentials Credentials { get; }


        /// <summary>
        /// Gets the IApiCarPremiumPolicyGetVariants.
        /// </summary>
        IApiCarPremiumPolicyGetVariants ApiCarPremiumPolicyGetVariants { get; }

            /// <summary>
        /// Acceptance check on current data
        /// </summary>
        /// <param name='viewModel'>
        /// Current data. Can include -1- Car details (licenseplate, price,
        /// security measurements, etc), -2- Most frequent driver details,
        /// -3- Risk assesment answers
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> ApiAcceptanceCheckPostWithHttpMessagesAsync(CarViewModel viewModel = default(CarViewModel), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Method for validating a zipcode
        /// </summary>
        /// <param name='zipCode'>
        /// The zipcode to validate
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<ReturnObjectZipCode>> ApiAddressLookupValidateZipcodePostWithHttpMessagesAsync(ZipCode zipCode = default(ZipCode), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Method for getting the full details of an address
        /// </summary>
        /// <param name='address'>
        /// Incomplete Address to fill with details
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<ReturnObjectAddress>> ApiAddressLookupGetFullAddressPostWithHttpMessagesAsync(Address address = default(Address), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Gets the discount amount(decimal) based on the provided code
        /// </summary>
        /// <param name='discountCode'>
        /// Discount code
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> ApiCarDiscountPolicyPostWithHttpMessagesAsync(string discountCode = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get all possible models of the provided brand car
        /// </summary>
        /// <param name='brand'>
        /// Brand of the car
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<ReturnObjectListString>> ApiCarLookupGetModelsPostWithHttpMessagesAsync(string brand = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get all editions of the provided brand and model car
        /// </summary>
        /// <param name='viewModel'>
        /// Model containing a brand(string) and model(string)
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> ApiCarLookupGetEditionsPostWithHttpMessagesAsync(CarLookupViewModel viewModel = default(CarLookupViewModel), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get the details (weight and catalog value) of the provided car
        /// </summary>
        /// <param name='viewModel'>
        /// Model containing a brand(string), model(string) and
        /// edition(string) of the car to get the weight for
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> ApiCarLookupGetEditionDetailsPostWithHttpMessagesAsync(CarLookupViewModel viewModel = default(CarLookupViewModel), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get the weight of the provided car
        /// </summary>
        /// <param name='viewModel'>
        /// Model containing a brand(string), model(string) and
        /// edition(string) of the car to get the weight for
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> ApiCarLookupGetWeightPostWithHttpMessagesAsync(CarLookupViewModel viewModel = default(CarLookupViewModel), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get the catalog value of the provided car
        /// </summary>
        /// <param name='viewModel'>
        /// Model containing a brand(string), model(string) and
        /// edition(string) of the car to get the catalog value for
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> ApiCarLookupGetCatalogValuePostWithHttpMessagesAsync(CarLookupViewModel viewModel = default(CarLookupViewModel), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get the policy documents for the chosen insurance
        /// </summary>
        /// <param name='viewModel'>
        /// CarViewModel
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> ApiCarPolicyDocumentGetDocumentsPostWithHttpMessagesAsync(CarViewModel viewModel = default(CarViewModel), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get Package Variants (MTPL || MTPL Limited Casco || MTPL All Risk)
        /// </summary>
        /// <param name='viewModel'>
        /// Viewmodel containg licenseplate, driver-age, -damagefreeyears,
        /// -residenceaddress zipcode and -kilometersPerYear
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> ApiCarPremiumPolicyGetVariantsPostWithHttpMessagesAsync(CarViewModel viewModel = default(CarViewModel), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get Coverages
        /// </summary>
        /// <param name='viewModel'>
        /// Viewmodel containg licenseplate, driver-age, -damagefreeyears and
        /// -residenceaddress zipcode
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> ApiCarPremiumPolicyGetCoveragesPostWithHttpMessagesAsync(CarViewModel viewModel = default(CarViewModel), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get Coverages and Variants
        /// </summary>
        /// <param name='viewModel'>
        /// Viewmodel containg licenseplate, driver-age, -damagefreeyears and
        /// -residenceaddress zipcode
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> ApiCarPremiumPolicyGetVariantsAndCoveragesPostWithHttpMessagesAsync(CarViewModel viewModel = default(CarViewModel), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get the discount based on the payment frequency
        /// </summary>
        /// <param name='viewModel'>
        /// Viewmodel containing the payment frequency
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> ApiCarPremiumPolicyPaymentFrequencyDiscountPostWithHttpMessagesAsync(CarViewModel viewModel = default(CarViewModel), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Returns the Car details of the car corresponding to the give
        /// license-plate
        /// </summary>
        /// <param name='licensePlate'>
        /// The license-plate from the car to get the details from
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> ApiLicensePlateLookupGetCarDetailsPostWithHttpMessagesAsync(LicensePlate licensePlate = default(LicensePlate), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

    }
}
